### ISSUE TITLE
Do not include border of viewfinder

### ISSUE THREAD

**Issue by cathoderaydude** [hbloom1783/Babel#17]
Adjust snap coordinates to only include space inside the viewfinder borders. This should be data-driven, probably, somehow?

**Comment by hbloom1783** [comment]
I think you fixed this by flooping the tab inside the viewfinder?  or did you want to exclude the border, too?  could the VF tab have a lil button on it to switch which side of the frame it's on?  (inside vs. outside I mean)

**Comment by cathoderaydude** [comment]
Yeah I consider this sorta fixed with the tab floop, with caveats - I should make the opacity of the entire viewfinder lower, or perhaps have it go translucent when your mouse isn't over it, so that you can see a little of what's under the border. It's not much but it could be important. Maybe even have a drawing mode where instead of full borders there's just four corner elements. Gotta try some experiments.

**Comment by cathoderaydude** [comment]
Made it translucent. Feels fine to me for now.
