### ISSUE TITLE
Fit phrase boxes to detected words

### ISSUE THREAD

**Issue by cathoderaydude** [hbloom1783/Babel#23]
When a phrase is created, it should snap (as an option) to the bounds of the words it matched. I tried doing this before but something went catastrophically wrong, need to try again.

**Comment by hbloom1783** [comment]
if you look at what the Corners() extension does and what the SelectMany linq method does, you should be able to make something that can be slammed into FitRect

**Comment by cathoderaydude** [comment]
This should be a toggle accessible from the toolbar
