### ISSUE TITLE
Implement Ctrl+C and toolbar copy on phrase

### ISSUE THREAD

**Issue by cathoderaydude** [hbloom1783/Babel#3]
Users should be able to copy the translated (and untranslated, somehow) text by clicking on a phrase and then hitting Ctrl+C or a toolbar button.

**Comment by hbloom1783** [comment]
right-click on a phraserect should have a context menu to copy the translated or raw text

ctrl-c could give you the text of the currently highlighted box, too

**Comment by cathoderaydude** [comment]
shit you're dead right, that's also a great place to start because we can dump things in there before they're ready to implement with more sophisticated UI.

I'm thinking multiple copy options should be available, like:

**Copy Translated** < default behavior of ctrl+c
**Copy Original**
**Copy Both** < produces output like the following:

[rawtext] translatedtext

Also, multi-select of phrase boxes should probably be enabled, and if you copy at that point you should get each box on a separate line with a full stop separating them, like:

[rawtext] translatedtext

[rawtext2] translatedtext2

[rawtext3] translatedtext3

**Comment by cathoderaydude** [comment]
This is implemented; skipped the toolbar options, don't think anyone would use them.
