### ISSUE TITLE
"Contains" mode

### ISSUE THREAD

**Issue by hbloom1783** [hbloom1783/Babel#33]
when smallboxes overlap, a phraserect that exactly fits a line of smallboxes frequently picks up a straggler from another line.  this can't be avoided currently without nudging the rects out of the way.  I propose:

1) make the phraserects only pick up smallboxes on Contains rather than on Intersects
2) make dragging a phraserect first do an intersects check, then fit itself exactly to the intersected rectangles, THEN do Contains to pick up text.  (you can also eliminate the minimum size this way)

**Comment by cathoderaydude** [comment]
Part 1 absolutely, part 2 should be a toggle as per #23

**Comment by cathoderaydude** [comment]
This should be set on a per-rect level, with a toolbar option to set which mode will be used by the next-created prect
